const laboratorio = {
  pacientes: [
    {
      id: "586c7618-1e7d-4212-a4ab-bea7b3aeadde",
      cedula: "V-12345678",
      nombre: "Juan",
      apellido: "Pérez",
      fechaNacimiento: "1990-05-15",
      telefono: "0424-1234567",
      email: "juan@email.com",
      direccion: "Calle 1, Casa 2, Barquisimeto",
      fechaRegistro: "2026-02-01",
    },
    {
      id: "b12549ad-5ca9-4681-9063-2914c1416750",
      cedula: "V-23456789",
      nombre: "María",
      apellido: "González",
      fechaNacimiento: "1985-08-20",
      telefono: "0414-2345678",
      email: "maria@email.com",
      direccion: "Avenida 2, Edificio 3, Apto 5",
      fechaRegistro: "2026-02-01",
    },
    {
      id: "cca90724-3f1a-4e28-8dea-f74ada645062",
      cedula: "V-34567890",
      nombre: "Carlos",
      apellido: "Rodríguez",
      fechaNacimiento: "1978-12-10",
      telefono: "0426-3456789",
      email: "carlos@email.com",
      direccion: "Calle Principal, Casa 15",
      fechaRegistro: "2026-02-01",
    },
    {
      id: "61b33d59-ee05-4029-a650-a01046553d94",
      cedula: "V-12345678",
      nombre: "Fausto",
      apellido: "Herrera",
      fechaNacimiento: "1968-03-27",
      telefono: "0424-9876543",
      email: "fas.her68@email.com",
      direccion: "Calle 5, Casa 22, Merida",
      fechaRegistro: "2026-02-01",
    },
  ],

  medicos: [
    {
      id: 1,
      cedula: "V-87654321",
      nombre: "Dra. María",
      apellido: "González",
      especialidad: "Medicina Interna",
      telefono: "0412-9876543",
      email: "maria.gonzalez@hospital.com",
      mpps: "12345",
    },
    {
      id: 2,
      cedula: "V-76543210",
      nombre: "Dr. Pedro",
      apellido: "Martínez",
      especialidad: "Cardiología",
      telefono: "0424-8765432",
      email: "pedro.martinez@hospital.com",
      mpps: "23456",
    },
    {
      id: 3,
      cedula: "V-65432109",
      nombre: "Dr. Luis",
      apellido: "Hernández",
      especialidad: "Endocrinología",
      telefono: "0414-7654321",
      email: "luis.hernandez@hospital.com",
      mpps: "34567",
    },
  ],
  ordenes: [
    {
      id: 1,
      pacienteId: 1,
      medicoId: 1,
      fechaOrden: "2025-01-20",
      estado: "completada",
      observaciones: "Paciente diabético, control rutinario",
      prioridad: "normal",
    },
    {
      id: 2,
      pacienteId: 2,
      medicoId: 2,
      fechaOrden: "2025-01-22",
      estado: "en_proceso",
      observaciones: "Paciente con antecedentes cardíacos",
      prioridad: "normal",
    },
    {
      id: 3,
      pacienteId: 3,
      medicoId: 3,
      fechaOrden: "2025-01-25",
      estado: "pendiente",
      observaciones: "Control de tiroides",
      prioridad: "urgente",
    },
    {
      id: 4,
      pacienteId: 1,
      medicoId: 1,
      fechaOrden: "2025-01-28",
      estado: "en_proceso",
      observaciones: "Seguimiento trimestral",
      prioridad: "normal",
    },
    {
      id: 5,
      pacienteId: 2,
      medicoId: 1,
      fechaOrden: "2025-01-29",
      estado: "pendiente",
      observaciones: "",
      prioridad: "normal",
    },
  ],

  detalleOrden: [
    {
      id: 1,
      ordenId: 1,
      tipoExamenId: 1,
      estado: "completado",
    },
    {
      id: 2,
      ordenId: 1,
      tipoExamenId: 2,
      estado: "completado",
    },
    {
      id: 3,
      ordenId: 2,
      tipoExamenId: 3,
      estado: "en_proceso",
    },
    {
      id: 4,
      ordenId: 2,
      tipoExamenId: 1,
      estado: "completado",
    },
    {
      id: 5,
      ordenId: 3,
      tipoExamenId: 4,
      estado: "pendiente",
    },
    {
      id: 6,
      ordenId: 4,
      tipoExamenId: 2,
      estado: "en_proceso",
    },
    {
      id: 7,
      ordenId: 4,
      tipoExamenId: 5,
      estado: "en_proceso",
    },
  ],

  resultados: [
    {
      id: 1,
      detalleOrdenId: 1,
      fechaRealizacion: "2025-01-21",
      valores: {
        Hemoglobina: "14.5 g/dL",
        Hematocrito: "42%",
        Leucocitos: "7500 /mm3",
        Plaquetas: "250000 /mm3",
        VCM: "88 fL",
        HCM: "30 pg",
      },
      observaciones: "Valores dentro de parámetros normales",
      responsable: "Bioanalista Carlos Ruiz",
    },
    {
      id: 2,
      detalleOrdenId: 2,
      fechaRealizacion: "2025-01-21",
      valores: {
        Glicemia: "95 mg/dL",
      },
      observaciones: "Glicemia normal",
      responsable: "Bioanalista Ana López",
    },
    {
      id: 3,
      detalleOrdenId: 4,
      fechaRealizacion: "2025-01-23",
      valores: {
        Hemoglobina: "13.8 g/dL",
        Hematocrito: "40%",
        Leucocitos: "6800 /mm3",
        Plaquetas: "220000 /mm3",
        VCM: "85 fL",
        HCM: "28 pg",
      },
      observaciones: "Resultados normales",
      responsable: "Bioanalista Carlos Ruiz",
    },
  ],
};

module.exports = laboratorio;
